### ISSUE TITLE
Adding Cheatsheet

### ISSUE THREAD

**Issue by PooriaT** [ab-anand/programming-books#25]
Hi,
I think that providing some cheatsheet as a pdf file is good for those ones who would like to access some syntaxes in a more convenient way. 

For Data Science lover:
http://www.utc.fr/~jlaforet/Suppl/python-cheatsheets.pdf

https://towardsdatascience.com/collecting-data-science-cheat-sheets-d2cdff092855

**Comment by ab-anand** [comment]
Hey @PooriaT ,
That definitely sounds like a great thing to have. Please feel free to raise PR if you can
